import { useState, type FormEvent } from "react";
import { earlyAccess } from "@/lib/landing-content";
import { ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const inputClasses = "w-full rounded-sm border border-input bg-card px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring";
export function EarlyAccess() {
  const [submitted, setSubmitted] = useState(false);
  const [open, setOpen] = useState(false);
  function handleSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSubmitted(true); }
  return <section id="early-access" className="scroll-mt-20 bg-shell px-4 py-10 text-shell-foreground sm:px-8 sm:py-12"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-[1.3fr_0.7fr] md:items-end md:gap-12"><div><p className="text-[10px] font-bold uppercase text-shell-foreground/65">03 / EARLY ACCESS</p><h2 className="mt-2 max-w-2xl font-display text-2xl font-bold leading-tight sm:text-3xl">{earlyAccess.headline}</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-shell-foreground/75">{earlyAccess.copy}</p></div><Button type="button" onClick={() => setOpen(true)} className="h-11 w-fit px-5 font-bold">{earlyAccess.cta} <ArrowUpRight /></Button></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="w-[calc(100%-2rem)] max-w-md rounded-md border-border bg-background p-5 sm:p-6"><DialogHeader className="text-left"><DialogTitle className="font-display text-xl font-bold">Join early access</DialogTitle><DialogDescription>Tell us a little about what you make.</DialogDescription></DialogHeader>{submitted ? <div role="status" className="border-l-[3px] border-primary bg-accent/50 p-4"><p className="font-semibold">Thanks for your interest.</p><p className="mt-1 text-sm text-muted-foreground">This preview doesn’t send signups yet. Please check back when early access opens.</p></div> : <form onSubmit={handleSubmit} className="space-y-3"><div><label htmlFor="ea-name" className="mb-1 block text-xs font-semibold">Name</label><input id="ea-name" name="name" type="text" required placeholder="e.g. Priya" className={inputClasses} /></div><div><label htmlFor="ea-handle" className="mb-1 block text-xs font-semibold">Instagram / WhatsApp handle</label><input id="ea-handle" name="handle" type="text" required placeholder="e.g. @priya.creates" className={inputClasses} /></div><div><label htmlFor="ea-craft" className="mb-1 block text-xs font-semibold">What do you make?</label><input id="ea-craft" name="craft" type="text" required placeholder="e.g. custom cakes, portraits, blouses…" className={inputClasses} /></div><Button type="submit" className="h-10 w-full font-bold">Join early access <ArrowUpRight /></Button><p className="text-xs text-muted-foreground">Preview only — your details are not sent or saved yet.</p></form>}</DialogContent></Dialog>
  </section>;
}
